version: '3'

services:
  db:
    image: mysql:5.7
    container_name: aivec_wp_mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
  phpmyadmin:
    container_name: aivec_wp_pma
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8070:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
volumes: 
  db_data: